% Sophie SAKKA 

% 20 frames corresponding to each of the 20 joints (F1~F20)
vars = genvarname({'F1','F2','F3','F4','F5','F6','F7','F8','F9','F10','F11','F12','F13','F14','F15','F16','F17','F18','F19','F20'});

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                               SKELETON                                  %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Plot skeleton (connect joint frames' origins)

linesIndex = [
    % LEFT LEG
    19  17; ...
    17  15; ...
    15  13; ...
    13   1; ...
    
    % RIGHT LEG
    20  18; ...
    18  16; ...
    16  14; ...
    14   1; ...
    
    % LEFT ARM
    11   9; ...
    9    7; ...
    7    5; ...
    5    3; ...
    
    % RIGHT ARM
    12  10; ...
    10   8; ...
    8    6; ...
    6    3; ...
    
    % TORSO
    1    2; ...
    2    3; ...
    
    % HEAD
    3    4 ...
    ];
lines = length(linesIndex(:,1));
for k = 1:lines
    eval([vars{linesIndex(k,1)} '_' vars{linesIndex(k,2)} '= line([T_'...
        vars{linesIndex(k,1)} '(1,4,1) T_' vars{linesIndex(k,2)} '(1,4,1)],[T_'...
        vars{linesIndex(k,1)} '(2,4,1) T_' vars{linesIndex(k,2)} '(2,4,1)],[T_'...
        vars{linesIndex(k,1)} '(3,4,1) T_' vars{linesIndex(k,2)} '(3,4,1)],''Color'',''k'',''LineWidth'',1.5);']);
end
